// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5kJ0rC3csSkdgx5c-QOjnXHEnV9s4sg',
    appId: '1:1035773338252:web:67a74ccf4f81e78f9691a9',
    messagingSenderId: '1035773338252',
    projectId: 'care-connect-3dbd7',
    authDomain: 'care-connect-3dbd7.firebaseapp.com',
    storageBucket: 'care-connect-3dbd7.firebasestorage.app',
    measurementId: 'G-EX337QRJV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3sHEwEK66GBUCp7wTMX6CCYVfrCsTVog',
    appId: '1:1035773338252:android:177d0b770a3d4f349691a9',
    messagingSenderId: '1035773338252',
    projectId: 'care-connect-3dbd7',
    storageBucket: 'care-connect-3dbd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-38ynV0IMaFiuFflNucc4TEylH3N8y0',
    appId: '1:1035773338252:ios:feb388b974748c899691a9',
    messagingSenderId: '1035773338252',
    projectId: 'care-connect-3dbd7',
    storageBucket: 'care-connect-3dbd7.firebasestorage.app',
    iosBundleId: 'com.example.clinicAppointmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_-38ynV0IMaFiuFflNucc4TEylH3N8y0',
    appId: '1:1035773338252:ios:feb388b974748c899691a9',
    messagingSenderId: '1035773338252',
    projectId: 'care-connect-3dbd7',
    storageBucket: 'care-connect-3dbd7.firebasestorage.app',
    iosBundleId: 'com.example.clinicAppointmentSystem',
  );
}
